### ISSUE TITLE
Products app doesn't work without SignIn application

### ISSUE THREAD

**Issue by diliger** [StarcounterSamples/Products#29]
First page of product opens fine but after page reload it redirects to some empty page with menu bar.

**Comment by diliger** [comment]
cc @tomalec @warpech

**Comment by warpech** [comment]
Can you provide some screenshot? What is the url where it redirects to?

**Comment by tomalec** [comment]
The URL stays the same
![products_wo_signin](https://cloud.githubusercontent.com/assets/17435/18183539/1fcf8fb6-7095-11e6-9565-d0f88a54f98e.gif)

**Comment by warpech** [comment]
I cannot reproduce it. Thanks for inspiring me to add an [issue template](https://github.com/StarcounterSamples/Products/blob/master/.github/ISSUE_TEMPLATE.md)

Please provide what is your Starcounter version and Launcher, Products versions

**Comment by tomalec** [comment]
### Steps to reproduce the behaviour
1. Run Launcher and Products app
2. Open the browser with http://localhost:8080/launcher
3. Click on "Products" icon
4. Click on any product from the list
5. Refresh the page

### Expected behaviour

Page after 5. should be the same as one after 4.

### Actual behaviour
Products standalone page is rendered in the workspace


### Technical information


##### Starcounter version
2.2.1.3018

##### Involved apps' version
- StarcounterPrefabs/Launcher@05efc44175
- StarcounterSamples/Products@0bda5da3c0

### Screenshot

![products_wo_signin](https://cloud.githubusercontent.com/assets/17435/18183539/1fcf8fb6-7095-11e6-9565-d0f88a54f98e.gif)

**Comment by tomalec** [comment]
Also related https://github.com/StarcounterSamples/Products/issues/30

**Comment by warpech** [comment]
Solved in #31. @diliger pls review.

**Comment by warpech** [comment]
Solved in #31
